import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GlobalStyle from '@/styles/Global'
import ClientThemeProvider from './ClientThemeProvider'
import { BaseLayout } from '@/components'
import './globals.css'
import StyledComponentsRegistry from './StyledComponentsRegistry'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Mercado de Fruta',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StyledComponentsRegistry>
                    <ClientThemeProvider>
                        <GlobalStyle />
                        <BaseLayout>{children}</BaseLayout>
                    </ClientThemeProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    )
}
