import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GlobalStyle from '@/styles/Global'
import ClientThemeProvider from './ClientThemeProvider'
import { BaseLayout } from '@/components'
import './globals.css'
import StyledComponentsRegistry from './StyledComponentsRegistry'
import { QueryClientProvider } from '@tanstack/react-query'
import { queryClient } from '@/utils/react-query'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Mercado de Fruta',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <QueryClientProvider client={queryClient}>
                    <StyledComponentsRegistry key="styled-components-registry">
                        <ClientThemeProvider key="client-theme-provider">
                            <GlobalStyle />
                            <BaseLayout>{children}</BaseLayout>
                        </ClientThemeProvider>
                    </StyledComponentsRegistry>
                </QueryClientProvider>
            </body>
        </html>
    )
}
